name: Build 
on:
    push:
        branches:
            - main
jobs:
    build-mac:
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.3.0"
            - name: Install dependencies
              run: npm ci
            - name: Decode and import signing certificate
              run: |
                  echo "${{ secrets.MACOS_CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
                  security create-keychain -p actions build.keychain
                  security default-keychain -s build.keychain
                  security unlock-keychain -p actions build.keychain
                  security import certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERTIFICATE_P12_PASSWORD }}" -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k actions build.keychain
            - name: Package and Notarize
              run: npm run make
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
                  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}